Debug: false # Used only for internal testing, recommend leaving this OFF
Locale: "en" # Language file to load, currently the plugin comes with en and no, but you can add your own custom language as well.


### Stock features moved from Movecraft

# AA Directors
AADirectorDistance: 50 # Max range at which fireballs will be redirected
AADirectorRange: 120 # Max range at which it will direct to a block vs in the general direction
AADirectorsAllowed: # List of string names to craft types that are allowed to use AA Directors
  - "Airship"
  - "SubAirship"

# Cannon Directors
CannonDirectorDistance: 100 # Max range at which TNT will be redirected
CannonDirectorRange: 120 # Max range at which it will direct to a block vs in the general direction
CannonDirectorsAllowed: # List of string names to craft types that are allowed to use Cannon Directors
  - "Airship"
  - "SubAirship"

# Directors
DirectorTool: STICK # Material name for director control.
TransparentBlocks: # List of MATERIAL_NAMES which are ignored for directing.  See https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html for a full list.
  - AIR
  - GLASS
  - THIN_GLASS
  - STAINED_GLASS
  - STAINED_GLASS_PANE
  - IRON_FENCE
  - REDSTONE_WIRE
  - IRON_TRAPDOOR
  - TRAP_DOOR
  - NETHER_BRICK_STAIRS
  - LEVER
  - STONE_BUTTON
  - WOOD_BUTTON
  - STEP
  - SMOOTH_STAIRS
  - SIGN
  - SIGN_POST
  - WALL_SIGN
  - CARPET

# Contact Explosives
EnableContactExplosives: true # Enable TNT contact explosives

# Durability Override
DurabilityOverride: # List of block IDs: ignore percent
  END_STONE: 80
  END_STONE_BRICKS: 80

# Fireball Lifespan
FireballLifespan: 6 # Lifespan of fireballs in seconds

# TNT Tracers
TracerRateTicks: 5.0 # Rate at which tracers are spawned on the path of flying TNT
TracerMinDistance: 60 # Minimum distance at which glowstone tracers are spawned on explosion
TracerParticles: FIREWORKS_SPARK # Particle to use for particle tracers  See https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html for options.
ExplosionParticles: VILLAGER_ANGRY # Particle to use for particle tracer explosions


### Custom features

# Damage Tracking
EnableFireballTracking: false # Enable tracking and recording of fireballs (higher lag than other tracking methods)
EnableTNTTracking: false # Enable tracking and recording of TNT damage (please read the wiki page before enabling!)
EnableTorpedoTracking: false # Enable tracking and recording of Torpedo damage
DamageTimeout: 300 # Timeout for damages in seconds

# Combat Release Tracking
EnableCombatReleaseTracking: false # Enable tracking of combat releasing
EnableCombatReleaseKick: true # Enable combat release kick, overriden to true if CombatReleaseBanLength isn't 0
CombatReleaseBanLength: 60 # Length of combat release ban in seconds, set to 0 to disable
CombatReleaseScuttle: true # Enable scuttling of crafts when combat released

# Anti-Player Radar
EnableAntiRadar: false # Enable invisibility for craft pilots to nullify minimap "player radar" modes

# Fire Behavior
EnableFireballPenetration: false # Randomly replace blocks with fire when they are struck by fireballs.
AddFiresToHitbox: true # Add fires lit on the surface of a craft to its hitbox so they don't obstruct it.

# Piston Behavior
ReImplementTranslocation: false